export const API_DOCS = [
  {
    category: "Authentication",
    endpoints: [
      {
        id: "auth-register",
        method: "POST",
        path: "/api/auth/register",
        description: "Register a new user account. Returns the created user and a JWT token.",
        auth: null,
        params: [],
        query: [],
        body: [
          { name: "name", type: "String", required: true, placeholder: "John Doe", description: "User's full name" },
          { name: "email", type: "String", required: true, placeholder: "user@example.com", description: "Valid email address" },
          { name: "password", type: "String", required: true, placeholder: "••••••••", description: "Minimum 8 characters" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "user", type: "Object", description: "Created user object" },
          { name: "user._id", type: "String", description: "MongoDB user ID" },
          { name: "user.name", type: "String", description: "User's display name" },
          { name: "user.email", type: "String", description: "User's email" },
          { name: "user.role", type: "String", description: "Account role: user | admin" },
          { name: "token", type: "String", description: "JWT authentication token" },
        ],
        errors: [
          { status: 400, reason: "Missing name, email, or password; email already in use" },
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "auth-login",
        method: "POST",
        path: "/api/auth/login",
        description: "Authenticate with email and password. Returns user data and a JWT token.",
        auth: null,
        params: [],
        query: [],
        body: [
          { name: "email", type: "String", required: true, placeholder: "user@example.com", description: "Registered email address" },
          { name: "password", type: "String", required: true, placeholder: "••••••••", description: "Account password" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "user", type: "Object", description: "Authenticated user object" },
          { name: "user._id", type: "String", description: "MongoDB user ID" },
          { name: "user.name", type: "String", description: "User's display name" },
          { name: "user.email", type: "String", description: "User's email" },
          { name: "user.role", type: "String", description: "Account role: user | admin" },
          { name: "token", type: "String", description: "JWT authentication token" },
        ],
        errors: [
          { status: 400, reason: "Missing or invalid email / password format" },
          { status: 401, reason: "Invalid credentials" },
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "auth-logout",
        method: "POST",
        path: "/api/auth/logout",
        description: "Invalidate the current session server-side. Requires a valid JWT token.",
        auth: "user",
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 401, reason: "Missing or invalid authorization token" },
        ],
      },
      {
        id: "auth-me-get",
        method: "GET",
        path: "/api/auth/me",
        description: "Retrieve the currently authenticated user's profile.",
        auth: "user",
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "user", type: "Object", description: "Authenticated user object" },
        ],
        errors: [
          { status: 401, reason: "Missing or invalid authorization token" },
        ],
      },
      {
        id: "auth-me-patch",
        method: "PATCH",
        path: "/api/auth/me",
        description: "Update the current user's name, email, or password.",
        auth: "user",
        params: [],
        query: [],
        body: [
          { name: "name", type: "String", required: false, placeholder: "New Name", description: "Updated display name" },
          { name: "email", type: "String", required: false, placeholder: "new@example.com", description: "Updated email address" },
          { name: "password", type: "String", required: false, placeholder: "newpassword", description: "Updated password (min 8 chars)" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "user", type: "Object", description: "Updated user object" },
        ],
        errors: [
          { status: 400, reason: "Invalid field value" },
          { status: 401, reason: "Missing or invalid authorization token" },
        ],
      },
      {
        id: "auth-me-delete",
        method: "DELETE",
        path: "/api/auth/me",
        description: "Permanently delete the current user's account.",
        auth: "user",
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 401, reason: "Missing or invalid authorization token" },
        ],
      },
      {
        id: "auth-admin",
        method: "GET",
        path: "/api/auth/admin",
        description: "Verify that the current token belongs to an admin user.",
        auth: "admin",
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true for admin" },
          { name: "user", type: "Object", description: "Admin user object" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions (not admin)" },
        ],
      },
    ],
  },
  {
    category: "Orders",
    endpoints: [
      {
        id: "orders-create",
        method: "POST",
        path: "/api/orders",
        description: "Submit a new service order. Services can be identified by MongoDB ID or by name. A confirmation email is sent to the company on success.",
        auth: null,
        params: [],
        query: [],
        body: [
          { name: "name", type: "String", required: true, placeholder: "Jane Doe", description: "Client's full name" },
          { name: "email", type: "String", required: true, placeholder: "client@example.com", description: "Client's email address" },
          { name: "category", type: "String", required: false, placeholder: "Design Services", description: "Service category label" },
          { name: "services", type: "Array<String>", required: true, placeholder: '["Logo Design","Brand Identity"]', description: "Service names or MongoDB ObjectIds" },
          { name: "message", type: "String", required: false, placeholder: "Optional project details", description: "Additional notes or requirements" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "order", type: "Object", description: "Created order object" },
          { name: "order._id", type: "String", description: "MongoDB order ID" },
          { name: "order.name", type: "String", description: "Client name" },
          { name: "order.email", type: "String", description: "Client email" },
          { name: "order.category", type: "String", description: "Service category" },
          { name: "order.services", type: "Array<ObjectId>", description: "Resolved service IDs" },
          { name: "order.total", type: "Number", description: "Calculated order total (after discounts)" },
          { name: "order.status", type: "String", description: "Order status: pending | confirmed | completed | cancelled" },
          { name: "order.details", type: "String", description: "Additional order details" },
          { name: "order.createdAt", type: "Date", description: "Order creation timestamp" },
        ],
        errors: [
          { status: 400, reason: "Missing name, email, or services; invalid service identifiers" },
          { status: 500, reason: "Internal server error or mail delivery failure" },
        ],
      },
      {
        id: "orders-list",
        method: "GET",
        path: "/api/orders",
        description: "Retrieve all orders sorted by newest first. Service references are populated.",
        auth: null,
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "orders", type: "Array<Object>", description: "All orders with populated service objects" },
        ],
        errors: [
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "orders-update",
        method: "PUT",
        path: "/api/orders/:id",
        description: "Update any field of an existing order. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB order ID" },
        ],
        query: [],
        body: [
          { name: "status", type: "String", required: false, placeholder: "confirmed", description: "Order status: pending | confirmed | completed | cancelled" },
          { name: "details", type: "String", required: false, placeholder: "Updated notes", description: "Updated order notes" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "order", type: "Object", description: "Updated order object with populated services" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 404, reason: "Order not found" },
        ],
      },
      {
        id: "orders-delete",
        method: "DELETE",
        path: "/api/orders/:id",
        description: "Permanently delete a single order by ID. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB order ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "orders-bulk-delete",
        method: "DELETE",
        path: "/api/orders",
        description: "Delete multiple orders by ID in a single request. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "ids", type: "Array<String>", required: true, placeholder: '["64a1b2c...","64a1b2d..."]', description: "Array of MongoDB order IDs to delete" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 400, reason: "ids must be a non-empty array" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
    ],
  },
  {
    category: "Services",
    endpoints: [
      {
        id: "services-create",
        method: "POST",
        path: "/api/services",
        description: "Create a new service entry in the catalog. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "name", type: "String", required: true, placeholder: "Logo Design", description: "Unique service name" },
          { name: "description", type: "String", required: false, placeholder: "Memorable brand identity mark", description: "Short service description" },
          { name: "price", type: "Number", required: false, placeholder: "150", description: "Base price in USD" },
          { name: "discount", type: "Number", required: false, placeholder: "10", description: "Discount percentage (0–100)" },
          { name: "duration", type: "Number", required: false, placeholder: "3", description: "Estimated duration in days" },
          { name: "revisits", type: "Number", required: false, placeholder: "3", description: "Number of revision rounds included" },
          { name: "category", type: "String", required: false, placeholder: "Design", description: "Service category: Design | Development" },
          { name: "icon", type: "String", required: false, placeholder: "FaFont", description: "react-icons icon component name" },
          { name: "href", type: "String", required: false, placeholder: "/services/logo", description: "Service detail page path" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "service", type: "Object", description: "Created service document" },
        ],
        errors: [
          { status: 400, reason: "Duplicate name or validation error" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "services-list",
        method: "GET",
        path: "/api/services",
        description: "Retrieve all services sorted by newest first.",
        auth: null,
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "services", type: "Array<Object>", description: "All service documents" },
        ],
        errors: [
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "services-get",
        method: "GET",
        path: "/api/services/:id",
        description: "Retrieve a single service by its MongoDB ID.",
        auth: null,
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB service ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "service", type: "Object", description: "Service document" },
        ],
        errors: [
          { status: 404, reason: "Service not found" },
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "services-update",
        method: "PUT",
        path: "/api/services/:id",
        description: "Update any field of an existing service. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB service ID" },
        ],
        query: [],
        body: [
          { name: "name", type: "String", required: false, placeholder: "Updated Name", description: "Service display name" },
          { name: "description", type: "String", required: false, placeholder: "Updated description", description: "Short service description" },
          { name: "price", type: "Number", required: false, placeholder: "200", description: "Updated base price" },
          { name: "discount", type: "Number", required: false, placeholder: "0", description: "Updated discount percentage" },
          { name: "duration", type: "Number", required: false, placeholder: "5", description: "Updated duration in days" },
          { name: "category", type: "String", required: false, placeholder: "Development", description: "Updated category" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "service", type: "Object", description: "Updated service document" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 404, reason: "Service not found" },
        ],
      },
      {
        id: "services-delete",
        method: "DELETE",
        path: "/api/services/:id",
        description: "Permanently delete a service by ID. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB service ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "services-bulk-delete",
        method: "DELETE",
        path: "/api/services",
        description: "Delete multiple services by ID in a single request. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "ids", type: "Array<String>", required: true, placeholder: '["64a1b2c...","64a1b2d..."]', description: "Array of MongoDB service IDs to delete" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 400, reason: "ids must be a non-empty array" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
    ],
  },
  {
    category: "Email",
    endpoints: [
      {
        id: "email-send",
        method: "POST",
        path: "/api/email",
        description: "Send a transactional email via the configured SMTP mailer. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "to", type: "String", required: true, placeholder: "recipient@example.com", description: "Recipient email address" },
          { name: "subject", type: "String", required: true, placeholder: "Hello from HestiQ", description: "Email subject line" },
          { name: "text", type: "String", required: false, placeholder: "Plain text body", description: "Plain-text version of the email body" },
          { name: "html", type: "String", required: false, placeholder: "<p>HTML body</p>", description: "HTML version of the email body" },
          { name: "replyTo", type: "String", required: false, placeholder: "noreply@example.com", description: "Reply-To header email address" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "message", type: "String", description: "Confirmation message" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 500, reason: "SMTP failure or mailer misconfiguration" },
        ],
      },
    ],
  },
  {
    category: "Analytics",
    endpoints: [
      {
        id: "analytics-track",
        method: "POST",
        path: "/api/analytics/track",
        description: "Track a single analytics event or a batch of up to 20 events. Accepts a single event object or a JSON array. Rate-limited to 60 requests per minute per IP.",
        auth: null,
        params: [],
        query: [],
        body: [
          { name: "event", type: "String", required: true, placeholder: "page_view", description: "Event name: page_view | session_start | order_created" },
          { name: "data", type: "Object", required: false, placeholder: '{"path":"/about"}', description: "Arbitrary event metadata (max nesting depth: 3)" },
          { name: "url", type: "String", required: false, placeholder: "https://example.com/about", description: "Page URL where the event occurred" },
          { name: "referrer", type: "String", required: false, placeholder: "https://google.com", description: "Referring page URL" },
          { name: "timestamp", type: "Number", required: false, placeholder: "1711200000000", description: "Unix millisecond timestamp; defaults to server time" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 400, reason: "Missing event field, or batch exceeds 20 events" },
          { status: 429, reason: "Rate limit exceeded (60 requests/min per IP)" },
        ],
      },
      {
        id: "analytics-traffic",
        method: "GET",
        path: "/api/analytics/traffic",
        description: "Get traffic overview: session visits, page views, unique visitors, and visit trend over time. Admin only.",
        auth: "admin",
        params: [],
        query: [
          { name: "period", type: "String", required: false, placeholder: "month", description: "Time window: day | month | year (default: month)" },
        ],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "data.visits", type: "Number", description: "Total session_start events in period" },
          { name: "data.pageviews", type: "Number", description: "Total page_view events in period" },
          { name: "data.unique", type: "Number", description: "Distinct visitor IDs in period" },
          { name: "data.trend", type: "Array<Object>", description: "Time-bucketed visit counts: [{label, count}]" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "analytics-source",
        method: "GET",
        path: "/api/analytics/source",
        description: "Get session breakdown by device type (desktop, tablet, mobile), based on session_start events. Admin only.",
        auth: "admin",
        params: [],
        query: [
          { name: "period", type: "String", required: false, placeholder: "month", description: "Time window: day | month | year (default: month)" },
        ],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "data.desktop", type: "Number", description: "Desktop session count" },
          { name: "data.tablet", type: "Number", description: "Tablet session count" },
          { name: "data.mobile", type: "Number", description: "Mobile session count" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "analytics-orders-stats",
        method: "GET",
        path: "/api/analytics/orders-stats",
        description: "Get order statistics: total count, current-month count, month-over-month change, and weekday distribution. Admin only.",
        auth: "admin",
        params: [],
        query: [
          { name: "period", type: "String", required: false, placeholder: "month", description: "Time window: day | month | year (default: month)" },
        ],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "data.total", type: "Number", description: "All-time total orders" },
          { name: "data.monthly", type: "Number", description: "Orders in the current calendar month" },
          { name: "data.change", type: "Number", description: "Month-over-month percentage change" },
          { name: "data.byWeekday", type: "Array<Object>", description: "Orders per weekday: [{day, count}]" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "analytics-users-stats",
        method: "GET",
        path: "/api/analytics/users-stats",
        description: "Get customer analytics: new vs returning customers and geographic breakdown, derived from order_created events. Admin only.",
        auth: "admin",
        params: [],
        query: [
          { name: "period", type: "String", required: false, placeholder: "month", description: "Time window: day | month | year (default: month)" },
        ],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "data.new", type: "Number", description: "First-time customers in period" },
          { name: "data.returning", type: "Number", description: "Returning customers in period" },
          { name: "data.geo", type: "Array<Object>", description: "Top 10 locations: [{country, city, count}]" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
    ],
  },
];
