export const API_DOCS = [
  {
    category: "Authentication",
    endpoints: [
      {
        id: "auth-register",
        method: "POST",
        path: "/auth/register",
        description: "Register a new user account. Returns the created user and a JWT token.",
        auth: null,
        params: [],
        query: [],
        body: [
          { name: "name", type: "String", required: true, placeholder: "John Doe", description: "User's full name" },
          { name: "email", type: "String", required: true, placeholder: "user@example.com", description: "Valid email address" },
          { name: "password", type: "String", required: true, placeholder: "••••••••", description: "Minimum 8 characters" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "user", type: "Object", description: "Created user object" },
          { name: "user._id", type: "String", description: "MongoDB user ID" },
          { name: "user.name", type: "String", description: "User's display name" },
          { name: "user.email", type: "String", description: "User's email" },
          { name: "user.role", type: "String", description: "Account role: user | admin" },
          { name: "token", type: "String", description: "JWT authentication token" },
        ],
        errors: [
          { status: 400, reason: "Missing name, email, or password; email already in use" },
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "auth-login",
        method: "POST",
        path: "/auth/login",
        description: "Authenticate with email and password. Returns user data and a JWT token.",
        auth: null,
        params: [],
        query: [],
        body: [
          { name: "email", type: "String", required: true, placeholder: "user@example.com", description: "Registered email address" },
          { name: "password", type: "String", required: true, placeholder: "••••••••", description: "Account password" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "user", type: "Object", description: "Authenticated user object" },
          { name: "user._id", type: "String", description: "MongoDB user ID" },
          { name: "user.name", type: "String", description: "User's display name" },
          { name: "user.email", type: "String", description: "User's email" },
          { name: "user.role", type: "String", description: "Account role: user | admin" },
          { name: "token", type: "String", description: "JWT authentication token" },
        ],
        errors: [
          { status: 400, reason: "Missing or invalid email / password format" },
          { status: 401, reason: "Invalid credentials" },
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "auth-logout",
        method: "POST",
        path: "/auth/logout",
        description: "Invalidate the current session server-side. Requires a valid JWT token.",
        auth: "user",
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 401, reason: "Missing or invalid authorization token" },
        ],
      },
      {
        id: "auth-me-get",
        method: "GET",
        path: "/auth/me",
        description: "Retrieve the currently authenticated user's profile.",
        auth: "user",
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "user", type: "Object", description: "Authenticated user object" },
        ],
        errors: [
          { status: 401, reason: "Missing or invalid authorization token" },
        ],
      },
      {
        id: "auth-me-patch",
        method: "PATCH",
        path: "/auth/me",
        description: "Update the current user's name, email, or password.",
        auth: "user",
        params: [],
        query: [],
        body: [
          { name: "name", type: "String", required: false, placeholder: "New Name", description: "Updated display name" },
          { name: "email", type: "String", required: false, placeholder: "new@example.com", description: "Updated email address" },
          { name: "password", type: "String", required: false, placeholder: "newpassword", description: "Updated password (min 8 chars)" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "user", type: "Object", description: "Updated user object" },
        ],
        errors: [
          { status: 400, reason: "Invalid field value" },
          { status: 401, reason: "Missing or invalid authorization token" },
        ],
      },
      {
        id: "auth-me-delete",
        method: "DELETE",
        path: "/auth/me",
        description: "Permanently delete the current user's account.",
        auth: "user",
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 401, reason: "Missing or invalid authorization token" },
        ],
      },
      {
        id: "auth-admin",
        method: "GET",
        path: "/auth/admin",
        description: "Verify that the current token belongs to an admin user.",
        auth: "admin",
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true for admin" },
          { name: "user", type: "Object", description: "Admin user object" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions (not admin)" },
        ],
      },
    ],
  },
  {
    category: "Orders",
    endpoints: [
      {
        id: "orders-create",
        method: "POST",
        path: "/orders",
        description: "Submit a new service order. Services can be identified by MongoDB ID or by name. A confirmation email is sent to the company on success.",
        auth: null,
        params: [],
        query: [],
        body: [
          { name: "name", type: "String", required: true, placeholder: "Jane Doe", description: "Client's full name" },
          { name: "email", type: "String", required: true, placeholder: "client@example.com", description: "Client's email address" },
          { name: "category", type: "String", required: false, placeholder: "Design Services", description: "Service category label" },
          { name: "services", type: "Array<String>", required: true, placeholder: '["Logo Design","Brand Identity"]', description: "Service names or MongoDB ObjectIds" },
          { name: "message", type: "String", required: false, placeholder: "Optional project details", description: "Additional notes or requirements" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "order", type: "Object", description: "Created order object" },
          { name: "order._id", type: "String", description: "MongoDB order ID" },
          { name: "order.name", type: "String", description: "Client name" },
          { name: "order.email", type: "String", description: "Client email" },
          { name: "order.category", type: "String", description: "Service category" },
          { name: "order.services", type: "Array<ObjectId>", description: "Resolved service IDs" },
          { name: "order.total", type: "Number", description: "Calculated order total (after discounts)" },
          { name: "order.status", type: "String", description: "Order status: pending | confirmed | completed | cancelled" },
          { name: "order.details", type: "String", description: "Additional order details" },
          { name: "order.createdAt", type: "Date", description: "Order creation timestamp" },
        ],
        errors: [
          { status: 400, reason: "Missing name, email, or services; invalid service identifiers" },
          { status: 500, reason: "Internal server error or mail delivery failure" },
        ],
      },
      {
        id: "orders-list",
        method: "GET",
        path: "/orders",
        description: "Retrieve all orders sorted by newest first. Service references are populated.",
        auth: null,
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "orders", type: "Array<Object>", description: "All orders with populated service objects" },
        ],
        errors: [
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "orders-update",
        method: "PUT",
        path: "/orders/:id",
        description: "Update any field of an existing order. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB order ID" },
        ],
        query: [],
        body: [
          { name: "status", type: "String", required: false, placeholder: "confirmed", description: "Order status: pending | confirmed | completed | cancelled" },
          { name: "details", type: "String", required: false, placeholder: "Updated notes", description: "Updated order notes" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "order", type: "Object", description: "Updated order object with populated services" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 404, reason: "Order not found" },
        ],
      },
      {
        id: "orders-delete",
        method: "DELETE",
        path: "/orders/:id",
        description: "Permanently delete a single order by ID. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB order ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "orders-bulk-delete",
        method: "DELETE",
        path: "/orders",
        description: "Delete multiple orders by ID in a single request. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "ids", type: "Array<String>", required: true, placeholder: '["64a1b2c...","64a1b2d..."]', description: "Array of MongoDB order IDs to delete" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 400, reason: "ids must be a non-empty array" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
    ],
  },
  {
    category: "Services",
    endpoints: [
      {
        id: "services-create",
        method: "POST",
        path: "/services",
        description: "Create a new service entry in the catalog. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "name", type: "String", required: true, placeholder: "Logo Design", description: "Unique service name" },
          { name: "description", type: "String", required: false, placeholder: "Memorable brand identity mark", description: "Short service description" },
          { name: "price", type: "Number", required: false, placeholder: "150", description: "Base price in USD" },
          { name: "discount", type: "Number", required: false, placeholder: "10", description: "Discount percentage (0–100)" },
          { name: "duration", type: "Number", required: false, placeholder: "3", description: "Estimated duration in days" },
          { name: "revisits", type: "Number", required: false, placeholder: "3", description: "Number of revision rounds included" },
          { name: "category", type: "String", required: false, placeholder: "Design", description: "Service category: Design | Development" },
          { name: "icon", type: "String", required: false, placeholder: "FaFont", description: "react-icons icon component name" },
          { name: "href", type: "String", required: false, placeholder: "/services/logo", description: "Service detail page path" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "service", type: "Object", description: "Created service document" },
        ],
        errors: [
          { status: 400, reason: "Duplicate name or validation error" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "services-list",
        method: "GET",
        path: "/services",
        description: "Retrieve all services sorted by newest first.",
        auth: null,
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "services", type: "Array<Object>", description: "All service documents" },
        ],
        errors: [
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "services-get",
        method: "GET",
        path: "/services/:id",
        description: "Retrieve a single service by its MongoDB ID.",
        auth: null,
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB service ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "service", type: "Object", description: "Service document" },
        ],
        errors: [
          { status: 404, reason: "Service not found" },
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "services-update",
        method: "PUT",
        path: "/services/:id",
        description: "Update any field of an existing service. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB service ID" },
        ],
        query: [],
        body: [
          { name: "name", type: "String", required: false, placeholder: "Updated Name", description: "Service display name" },
          { name: "description", type: "String", required: false, placeholder: "Updated description", description: "Short service description" },
          { name: "price", type: "Number", required: false, placeholder: "200", description: "Updated base price" },
          { name: "discount", type: "Number", required: false, placeholder: "0", description: "Updated discount percentage" },
          { name: "duration", type: "Number", required: false, placeholder: "5", description: "Updated duration in days" },
          { name: "category", type: "String", required: false, placeholder: "Development", description: "Updated category" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "service", type: "Object", description: "Updated service document" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 404, reason: "Service not found" },
        ],
      },
      {
        id: "services-delete",
        method: "DELETE",
        path: "/services/:id",
        description: "Permanently delete a service by ID. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB service ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "services-bulk-delete",
        method: "DELETE",
        path: "/services",
        description: "Delete multiple services by ID in a single request. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "ids", type: "Array<String>", required: true, placeholder: '["64a1b2c...","64a1b2d..."]', description: "Array of MongoDB service IDs to delete" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 400, reason: "ids must be a non-empty array" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
    ],
  },
  {
    category: "Email",
    endpoints: [
      {
        id: "email-send",
        method: "POST",
        path: "/email",
        description: "Send a transactional email via the configured SMTP mailer. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "to", type: "String", required: true, placeholder: "recipient@example.com", description: "Recipient email address" },
          { name: "subject", type: "String", required: true, placeholder: "Hello from HestiQ", description: "Email subject line" },
          { name: "text", type: "String", required: false, placeholder: "Plain text body", description: "Plain-text version of the email body" },
          { name: "html", type: "String", required: false, placeholder: "<p>HTML body</p>", description: "HTML version of the email body" },
          { name: "replyTo", type: "String", required: false, placeholder: "noreply@example.com", description: "Reply-To header email address" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "message", type: "String", description: "Confirmation message" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 500, reason: "SMTP failure or mailer misconfiguration" },
        ],
      },
    ],
  },
  {
    category: "Analytics",
    endpoints: [
      {
        id: "analytics-track",
        method: "POST",
        path: "/analytics/track",
        description: "Track a single analytics event or a batch of up to 20 events. Accepts a single event object or a JSON array. Rate-limited to 60 requests per minute per IP.",
        auth: null,
        params: [],
        query: [],
        body: [
          { name: "event", type: "String", required: true, placeholder: "page_view", description: "Event name: page_view | session_start | order_created" },
          { name: "data", type: "Object", required: false, placeholder: '{"path":"/about"}', description: "Arbitrary event metadata (max nesting depth: 3)" },
          { name: "url", type: "String", required: false, placeholder: "https://example.com/about", description: "Page URL where the event occurred" },
          { name: "referrer", type: "String", required: false, placeholder: "https://google.com", description: "Referring page URL" },
          { name: "timestamp", type: "Number", required: false, placeholder: "1711200000000", description: "Unix millisecond timestamp; defaults to server time" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 400, reason: "Missing event field, or batch exceeds 20 events" },
          { status: 429, reason: "Rate limit exceeded (60 requests/min per IP)" },
        ],
      },
      {
        id: "analytics-traffic",
        method: "GET",
        path: "/analytics/traffic",
        description: "Get traffic overview: session visits, page views, unique visitors, and visit trend over time. Admin only.",
        auth: "admin",
        params: [],
        query: [
          { name: "period", type: "String", required: false, placeholder: "month", description: "Time window: day | month | year (default: month)" },
        ],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "data.visits", type: "Number", description: "Total session_start events in period" },
          { name: "data.pageviews", type: "Number", description: "Total page_view events in period" },
          { name: "data.unique", type: "Number", description: "Distinct visitor IDs in period" },
          { name: "data.trend", type: "Array<Object>", description: "Time-bucketed visit counts: [{label, count}]" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "analytics-source",
        method: "GET",
        path: "/analytics/source",
        description: "Get session breakdown by device type (desktop, tablet, mobile), based on session_start events. Admin only.",
        auth: "admin",
        params: [],
        query: [
          { name: "period", type: "String", required: false, placeholder: "month", description: "Time window: day | month | year (default: month)" },
        ],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "data.desktop", type: "Number", description: "Desktop session count" },
          { name: "data.tablet", type: "Number", description: "Tablet session count" },
          { name: "data.mobile", type: "Number", description: "Mobile session count" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "analytics-orders-stats",
        method: "GET",
        path: "/analytics/orders-stats",
        description: "Get order statistics: total count, current-month count, month-over-month change, and weekday distribution. Admin only.",
        auth: "admin",
        params: [],
        query: [
          { name: "period", type: "String", required: false, placeholder: "month", description: "Time window: day | month | year (default: month)" },
        ],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "data.total", type: "Number", description: "All-time total orders" },
          { name: "data.monthly", type: "Number", description: "Orders in the current calendar month" },
          { name: "data.change", type: "Number", description: "Month-over-month percentage change" },
          { name: "data.byWeekday", type: "Array<Object>", description: "Orders per weekday: [{day, count}]" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "analytics-users-stats",
        method: "GET",
        path: "/analytics/users-stats",
        description: "Get customer analytics: new vs returning customers and geographic breakdown, derived from order_created events. Admin only.",
        auth: "admin",
        params: [],
        query: [
          { name: "period", type: "String", required: false, placeholder: "month", description: "Time window: day | month | year (default: month)" },
        ],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "data.new", type: "Number", description: "First-time customers in period" },
          { name: "data.returning", type: "Number", description: "Returning customers in period" },
          { name: "data.geo", type: "Array<Object>", description: "Top 10 locations: [{country, city, count}]" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
    ],
  },
  {
    category: "Team",
    endpoints: [
      {
        id: "team-create",
        method: "POST",
        path: "/team",
        description: "Create a new team member. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "name", type: "String", required: true, placeholder: "Jane Doe", description: "Team member's full name" },
          { name: "email", type: "String", required: true, placeholder: "jane@example.com", description: "Unique email address" },
          { name: "title", type: "String", required: false, placeholder: "Lead Designer", description: "Job title or role" },
          { name: "image", type: "String", required: false, placeholder: "/files/64a1b2c3d4e5f6789abcdef0", description: "Image URL from files API" },
          { name: "tags", type: "Array<String>", required: false, placeholder: '["design","management"]', description: "Tags: management | design | development | marketing" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "member", type: "Object", description: "Created team member document" },
        ],
        errors: [
          { status: 400, reason: "Missing name or email; invalid tag values" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "team-list",
        method: "GET",
        path: "/team",
        description: "Retrieve all team members sorted by newest first.",
        auth: null,
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "members", type: "Array<Object>", description: "All team member documents" },
        ],
        errors: [
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "team-get",
        method: "GET",
        path: "/team/:id",
        description: "Retrieve a single team member by MongoDB ID.",
        auth: null,
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB team member ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "member", type: "Object", description: "Team member document" },
        ],
        errors: [
          { status: 404, reason: "Team member not found" },
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "team-update",
        method: "PATCH",
        path: "/team/:id",
        description: "Update a team member. If the image URL changes, the old image is deleted from storage. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB team member ID" },
        ],
        query: [],
        body: [
          { name: "name", type: "String", required: false, placeholder: "Jane Doe", description: "Updated full name" },
          { name: "email", type: "String", required: false, placeholder: "jane@example.com", description: "Updated email address" },
          { name: "title", type: "String", required: false, placeholder: "Senior Designer", description: "Updated job title" },
          { name: "image", type: "String", required: false, placeholder: "/files/64a1b2c3d4e5f6789abcdef0", description: "Updated image URL" },
          { name: "tags", type: "Array<String>", required: false, placeholder: '["development"]', description: "Updated tags array" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "member", type: "Object", description: "Updated team member document" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 404, reason: "Team member not found" },
        ],
      },
      {
        id: "team-delete",
        method: "DELETE",
        path: "/team/:id",
        description: "Delete a team member and their associated image from storage. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB team member ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 404, reason: "Team member not found" },
        ],
      },
      {
        id: "team-bulk-delete",
        method: "DELETE",
        path: "/team",
        description: "Delete multiple team members and their images in a single request. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "ids", type: "Array<String>", required: true, placeholder: '["64a1b2c...","64a1b2d..."]', description: "Array of MongoDB team member IDs" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 400, reason: "ids must be a non-empty array" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
    ],
  },
  {
    category: "Files",
    endpoints: [
      {
        id: "files-upload",
        method: "POST",
        path: "/files",
        description: "Upload an image file to GridFS storage. Accepts multipart/form-data with a 'file' field. Max size 10 MB. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "file", type: "File", required: true, placeholder: "(binary)", description: "Image file (multipart/form-data, field name: file)" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "id", type: "String", description: "GridFS file ID" },
          { name: "url", type: "String", description: "Relative URL to retrieve the file: /files/:id" },
        ],
        errors: [
          { status: 400, reason: "No file provided or non-image MIME type" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 413, reason: "File exceeds 10 MB size limit" },
        ],
      },
      {
        id: "files-list",
        method: "GET",
        path: "/files",
        description: "List all stored files sorted by upload date descending. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "files", type: "Array<Object>", description: "GridFS file documents" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "files-get",
        method: "GET",
        path: "/files/:id",
        description: "Stream a file by its GridFS ID. Returns the raw binary with appropriate Content-Type. Publicly accessible.",
        auth: null,
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "GridFS file ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "(binary stream)", type: "Buffer", description: "Raw file data with Content-Type header set" },
        ],
        errors: [
          { status: 400, reason: "Invalid file ID format" },
          { status: 404, reason: "File not found" },
        ],
      },
      {
        id: "files-delete",
        method: "DELETE",
        path: "/files/:id",
        description: "Permanently delete a file from GridFS storage by ID. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "GridFS file ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 400, reason: "Invalid file ID format" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 404, reason: "File not found" },
        ],
      },
    ],
  },
  {
    category: "Jobs",
    endpoints: [
      {
        id: "jobs-list",
        method: "GET",
        path: "/jobs",
        description: "List jobs. Without authentication, returns only active jobs (applicants excluded). With a valid admin token, returns all jobs including applicants.",
        auth: null,
        params: [],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "jobs", type: "Array<Object>", description: "Job documents. Applicants array included only for admins." },
        ],
        errors: [
          { status: 500, reason: "Internal server error" },
        ],
      },
      {
        id: "jobs-create",
        method: "POST",
        path: "/jobs",
        description: "Create a new job posting. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "title", type: "String", required: true, placeholder: "Frontend Developer", description: "Job title" },
          { name: "description", type: "String", required: false, placeholder: "We're looking for...", description: "Full job description" },
          { name: "location", type: "String", required: false, placeholder: "Remote", description: "Job location (default: Remote)" },
          { name: "type", type: "String", required: false, placeholder: "Full-time", description: "Employment type: Part-time | Full-time | Contract | Internship" },
          { name: "salary.min", type: "Number", required: false, placeholder: "3000", description: "Minimum salary" },
          { name: "salary.max", type: "Number", required: false, placeholder: "6000", description: "Maximum salary" },
          { name: "salary.currency", type: "String", required: false, placeholder: "USD", description: "Salary currency" },
          { name: "skills", type: "Array<String>", required: false, placeholder: '["React","Node.js"]', description: "Required skills" },
          { name: "status", type: "String", required: false, placeholder: "active", description: "Job status: active | closed" },
          { name: "postedAt", type: "Date", required: false, placeholder: "2025-01-01", description: "Post date (default: now)" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "job", type: "Object", description: "Created job document" },
        ],
        errors: [
          { status: 400, reason: "Missing title or validation error" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "jobs-update",
        method: "PUT",
        path: "/jobs/:id",
        description: "Update a job posting. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB job ID" },
        ],
        query: [],
        body: [
          { name: "title", type: "String", required: false, placeholder: "Updated Title", description: "Job title" },
          { name: "description", type: "String", required: false, placeholder: "Updated description", description: "Job description" },
          { name: "location", type: "String", required: false, placeholder: "Remote", description: "Job location" },
          { name: "type", type: "String", required: false, placeholder: "Contract", description: "Employment type" },
          { name: "salary", type: "Object", required: false, placeholder: '{"min":2000,"max":5000,"currency":"USD"}', description: "Salary range object" },
          { name: "skills", type: "Array<String>", required: false, placeholder: '["TypeScript"]', description: "Required skills" },
          { name: "status", type: "String", required: false, placeholder: "closed", description: "Job status: active | closed" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "job", type: "Object", description: "Updated job document" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 404, reason: "Job not found" },
        ],
      },
      {
        id: "jobs-delete",
        method: "DELETE",
        path: "/jobs/:id",
        description: "Permanently delete a job posting by ID. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB job ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 404, reason: "Job not found" },
        ],
      },
      {
        id: "jobs-bulk-delete",
        method: "DELETE",
        path: "/jobs",
        description: "Delete multiple job postings by ID. Admin only.",
        auth: "admin",
        params: [],
        query: [],
        body: [
          { name: "ids", type: "Array<String>", required: true, placeholder: '["64a1b2c...","64a1b2d..."]', description: "Array of MongoDB job IDs to delete" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 400, reason: "ids must be a non-empty array" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
        ],
      },
      {
        id: "jobs-apply",
        method: "POST",
        path: "/jobs/:id/apply",
        description: "Submit a job application. Accepts multipart/form-data. An optional resume file (PDF or Word, max 5 MB) can be attached. The job must be active.",
        auth: null,
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB job ID" },
        ],
        query: [],
        body: [
          { name: "firstName", type: "String", required: true, placeholder: "Jane", description: "Applicant first name" },
          { name: "lastName", type: "String", required: true, placeholder: "Doe", description: "Applicant last name" },
          { name: "email", type: "String", required: true, placeholder: "jane@example.com", description: "Applicant email address" },
          { name: "phone", type: "String", required: false, placeholder: "+1 555 000 0000", description: "Applicant phone number" },
          { name: "message", type: "String", required: false, placeholder: "I'm excited to apply...", description: "Cover letter or message" },
          { name: "resume", type: "File", required: false, placeholder: "(binary)", description: "CV/resume file (PDF or DOCX, max 5 MB, multipart field: resume)" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 400, reason: "Missing firstName, lastName, or email; invalid file type" },
          { status: 404, reason: "Job not found or not accepting applications" },
          { status: 413, reason: "Resume file exceeds 5 MB" },
        ],
      },
      {
        id: "jobs-applicant-update",
        method: "PATCH",
        path: "/jobs/:id/applicants/:applicantId",
        description: "Update an applicant's record (e.g. change status). Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB job ID" },
          { name: "applicantId", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef1", description: "Applicant subdocument ID" },
        ],
        query: [],
        body: [
          { name: "status", type: "String", required: false, placeholder: "reviewing", description: "Applicant status: pending | reviewing | accepted | rejected" },
          { name: "firstName", type: "String", required: false, placeholder: "Jane", description: "Updated first name" },
          { name: "lastName", type: "String", required: false, placeholder: "Doe", description: "Updated last name" },
          { name: "email", type: "String", required: false, placeholder: "jane@example.com", description: "Updated email" },
          { name: "phone", type: "String", required: false, placeholder: "+1 555 000 0000", description: "Updated phone" },
          { name: "message", type: "String", required: false, placeholder: "Cover letter", description: "Updated message" },
        ],
        response: [
          { name: "success", type: "Boolean", description: "Operation result" },
          { name: "applicant", type: "Object", description: "Updated applicant subdocument" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 404, reason: "Job or applicant not found" },
        ],
      },
      {
        id: "jobs-applicant-delete",
        method: "DELETE",
        path: "/jobs/:id/applicants/:applicantId",
        description: "Remove an applicant from a job. Admin only.",
        auth: "admin",
        params: [
          { name: "id", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "MongoDB job ID" },
          { name: "applicantId", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef1", description: "Applicant subdocument ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "success", type: "Boolean", description: "Always true on success" },
        ],
        errors: [
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 404, reason: "Job or applicant not found" },
        ],
      },
      {
        id: "jobs-resume-download",
        method: "GET",
        path: "/jobs/resumes/:fileId",
        description: "Download an applicant's resume from GridFS storage. Returns the file as an attachment. Admin only.",
        auth: "admin",
        params: [
          { name: "fileId", type: "String", required: true, placeholder: "64a1b2c3d4e5f6789abcdef0", description: "GridFS resume file ID" },
        ],
        query: [],
        body: [],
        response: [
          { name: "(binary stream)", type: "Buffer", description: "Raw resume file with Content-Disposition: attachment" },
        ],
        errors: [
          { status: 400, reason: "Invalid file ID format" },
          { status: 401, reason: "Not authenticated" },
          { status: 403, reason: "Insufficient permissions" },
          { status: 404, reason: "Resume not found" },
        ],
      },
    ],
  },
];
