const services = [
  {
    name: "Logo Design",
    description: "Memorable brand identity mark",
    price: 150,
    duration: 3,
    revisits: 3,
    category: "Design",
    icon: "FaFont",
    href: "/services/logo",
  },
  {
    name: "Brand Identity",
    description: "Comprehensive brand identity package",
    price: 300,
    duration: 5,
    revisits: 5,
    category: "Design",
    icon: "FaPalette",
    href: "/services/brand-identity",
  },
  {
    name: "Advertisement Design",
    description: "Creative advertisement design services",
    price: 50,
    duration: 1,
    revisits: 3,
    category: "Design",
    icon: "FaBullhorn",
    href: "/services/advertisement-design",
  },
  {
    name: "Poster Design",
    description: "Eye-catching poster design services",
    price: 50,
    duration: 1,
    revisits: 2,
    category: "Design",
    icon: "FaFileImage",
    href: "/services/poster-design",
  },
  {
    name: "UI/UX Design",
    description: "User interface and user experience design services",
    price: 150,
    duration: 5,
    revisits: 5,
    category: "Design",
    icon: "FaLaptopCode",
    href: "/services/ui-ux-design",
  },
  {
    name: "Illustration",
    description: "Custom digital or print artwork",
    price: 100,
    duration: 3,
    revisits: 2,
    category: "Design",
    icon: "FaPaintbrush",
    href: "/services/illustration",
  },
  {
    name: "Web Application",
    description: "Scalable web applications with modern technologies",
    price: 400,
    duration: 3,
    revisits: 5,
    category: "Development",
    icon: "FaGlobe",
    href: "/services/web-application",
  },
  {
    name: "Mobile Application",
    description: "High-performance mobile applications for iOS and Android",
    price: 500,
    duration: 5,
    revisits: 5,
    category: "Development",
    icon: "FaMobileScreenButton",
    href: "/services/mobile-application",
  },
  {
    name: "E-commerce Platform",
    description: "Robust e-commerce solutions for online businesses",
    price: 600,
    duration: 6,
    revisits: 5,
    category: "Development",
    icon: "FaCartShopping",
    href: "/services/e-commerce-platform",
  },
  {
    name: "Single Page Website",
    description: "Responsive single page website design",
    price: 100,
    duration: 2,
    revisits: 3,
    category: "Development",
    icon: "FaFileCode",
    href: "/services/single-page-website",
  },
  {
    name: "Business Website",
    description: "Professional websites for companies and brands",
    price: 250,
    duration: 4,
    revisits: 5,
    category: "Development",
    icon: "FaSuitcase",
    href: "/services/business-website",
  },
  {
    name: "Maintenance & Hosting",
    description: "Ongoing maintenance and hosting services",
    category: "Development",
    icon: "FaServer",
    href: "/services/maintenance-hosting",
  },
];

export default services;